"use client";

import React from "react";
import { Button } from "@/components/ui/Button";

import ArrowRightSLineIcon from "remixicon-react/ArrowRightSLineIcon";
import ArrowLeftSLineIcon from "remixicon-react/ArrowLeftSLineIcon";
import FileCopyLineIcon from "remixicon-react/FileCopyLineIcon";

export default function Buttons() {
  return (
    <div className="p-4 flex justify-center gap-4 flex-wrap">
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button variant={"primary"} icon={FileCopyLineIcon} />
            </li>
            <li>
              <Button variant={"primary"} icon={FileCopyLineIcon} loading />
            </li>
            <li>
              <Button variant={"primary"} icon={FileCopyLineIcon} isDisabled />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button variant={"neutral"} icon={FileCopyLineIcon} />
            </li>
            <li>
              <Button variant={"neutral"} icon={FileCopyLineIcon} loading />
            </li>
            <li>
              <Button variant={"neutral"} icon={FileCopyLineIcon} isDisabled />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button variant={"error"} icon={FileCopyLineIcon} />
            </li>
            <li>
              <Button variant={"error"} icon={FileCopyLineIcon} loading />
            </li>
            <li>
              <Button variant={"error"} icon={FileCopyLineIcon} isDisabled />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>

      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button size="small" variant={"error"} icon={FileCopyLineIcon} />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>

      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"primary"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"neutral"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
      <section className="flex flex-wrap">
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"stroke"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"lighter"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
        <div className="flex gap-4 p-4">
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                loading
              >
                Button
              </Button>
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                iconLeft={ArrowLeftSLineIcon}
                iconRight={ArrowRightSLineIcon}
                isDisabled
              >
                Button
              </Button>
            </li>
          </ul>
          <ul className="flex flex-col gap-4">
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                loading
              />
            </li>
            <li>
              <Button
                size="x-small"
                variant={"error"}
                modifier={"ghost"}
                icon={FileCopyLineIcon}
                isDisabled
              />
            </li>
          </ul>
        </div>
      </section>
    </div>
  );
}
